print(True and True )
print(False and True )
print(1==1 and 2==1)
print(1==1 or 2==1)
print("love"=="love")
print(1==1 and 2!= 1)
print(1==1 or 2!=1)
print(True and 1==1)
print(True or 1==1)
print(False and 0 !=0)
print("time"=="memory")
print(1!=0 and 2==1)
print("Butter"!="butter")
print("one"==1)